### ISSUE TITLE
Address in use errors

### ISSUE THREAD

**Issue by martinthomson** [private-attribution/ipa#508]
```
---- net::transport::e2e_tests::fails_if_not_subscribed stdout ----
thread 'net::transport::e2e_tests::fails_if_not_subscribed' panicked at 'Failed to serve: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/net/server/mod.rs:77:26
thread 'net::transport::e2e_tests::fails_if_not_subscribed' panicked at 'Failed to bind server to a port', src/net/server/mod.rs:95:14
```

**Comment by andyleiserson** [comment]
I believe we haven't seen this in a long time, so I'm going to close this issue.
